plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

group = 'com.oodesigns.modbus'
version = '0.1.0-SNAPSHOT'

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.19.2'
    implementation 'com.digitalpetri.modbus:modbus-tcp:2.1.0'
    implementation 'com.digitalpetri.modbus:modbus-serial:2.1.0'
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
